Repository boostcampwm2023/web12-algo-with-me, pull requests merged in 2023-11, with the labels that each got.

#27 feat: typeorm 연동, db 연동
  be/algo-with-me-api/.gitignore
  be/algo-with-me-api/package.json
  be/algo-with-me-api/pnpm-lock.yaml
  be/algo-with-me-api/src/app.module.ts
Labels: BE

#35 [#33] editor 연동
  frontend/.eslintrc.cjs
  frontend/.prettierrc
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.tsx
  frontend/src/components/ContestPage.tsx
  frontend/src/components/Editor.tsx
  frontend/styled-system/types/parts.d.ts
Labels: FE

#42 [#17] 문제 보기 컴포넌트 작성
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/ContestPage.tsx
  frontend/src/components/MarkdownComponent.tsx
  frontend/src/components/ProblemContent.tsx
  frontend/src/mockData.json
Labels: review, FE

#65 [#56] FE CI/CD main.yml 파일 수정
  .github/workflows/main.yml
Labels: review, FE

#44 [#19] 대회 정보 표시
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/ContestBreadCrumb.tsx
  frontend/src/components/ContestPage.tsx
  frontend/src/components/MarkdownComponent.tsx
  frontend/src/components/ProblemContent.tsx
  frontend/src/components/TestResult.tsx
  frontend/src/components/submissionResult/ResultInfo.tsx
  frontend/src/components/submissionResult/ResultInfoWrapper.tsx
  frontend/src/components/submissionResult/ResultList.tsx
  frontend/src/components/submissionResult/types.ts
  frontend/src/components/types.ts
  frontend/src/constants/index.ts
  frontend/styled-system/types/parts.d.ts
Labels: FE

#86 [#85] 문제 보기
  frontend/src/components/Contest/ContestBreadCrumb.tsx
  frontend/src/pages/ProblemPage.tsx
  frontend/src/router.tsx
Labels: FE

#88 [#54] 유저 회원가입로그인 구현
  be/algo-with-me-api/package.json
  be/algo-with-me-api/pnpm-lock.yaml
  be/algo-with-me-api/src/app.module.ts
  be/algo-with-me-api/src/auth/auth.module.ts
  be/algo-with-me-api/src/auth/auth.strategy.ts
  be/algo-with-me-api/src/auth/controllers/auth.controller.ts
  be/algo-with-me-api/src/auth/services/auth.service.ts
  be/algo-with-me-api/src/main.ts
  be/algo-with-me-api/src/user/dto/user.response.dto.ts
  be/algo-with-me-api/src/user/entities/user.entity.ts
  be/algo-with-me-api/src/user/services/user.service.ts
  be/algo-with-me-api/src/user/user.module.ts
Labels: BE

#92 [#91] 문제 보기 api 연동
  frontend/src/hooks/competition/useCompetition.ts
  frontend/src/hooks/problem/useProblem.ts
  frontend/src/pages/ContestPage.tsx
  frontend/src/pages/ProblemPage.tsx
  frontend/src/router.tsx
Labels: FE

#96 [#95] 깃허브 로그인 완료시 프론트 url로 리디렉션 되도록 수정
  be/algo-with-me-api/src/auth/controllers/auth.controller.ts
Labels: BE

#98 [#77] 메인 페이지
  frontend/src/components/Main/Buttons/GoToCreateCompetitionLink.tsx
  frontend/src/components/Main/Buttons/JoinCompetitionButton.tsx
  frontend/src/components/Main/Buttons/ViewDashboardButton.tsx
  frontend/src/components/Main/CompetitionList.tsx
  frontend/src/constants/index.ts
  frontend/src/pages/MainPage.tsx
  frontend/src/router.tsx
  frontend/src/utils/secToTime.ts
Labels: FE

#102 [#99] 로그인 페이지 구현
  frontend/index.html
  frontend/src/components/Login/index.tsx
  frontend/src/components/Problem/Markdown.tsx
  frontend/src/components/submissionResult/ResultList.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/vite.config.ts
Labels: FE

#108 [#57] 유저 대회 구현을 완료하면 db dto 등을 그에 맞춰 변경하기
  be/algo-with-me-api/src/auth/auth.strategy.ts
  be/algo-with-me-api/src/auth/controllers/auth.controller.ts
  be/algo-with-me-api/src/competition/controllers/competition.controller.ts
  be/algo-with-me-api/src/competition/dto/create-competition.dto.ts
  be/algo-with-me-api/src/competition/entities/competition.entity.ts
  be/algo-with-me-api/src/competition/entities/competition.problem.entity.ts
  be/algo-with-me-api/src/competition/entities/submission.entity.ts
  be/algo-with-me-api/src/user/decorators/user.decorators.ts
  be/algo-with-me-api/src/user/dto/user.response.dto.ts
  be/algo-with-me-api/src/user/entities/user.entity.ts
Labels: BE

#112 [#60] websocket 추가 구현
  be/algo-with-me-api/src/auth/auth.module.ts
  be/algo-with-me-api/src/auth/dto/auth.token.payload.dto.ts
  be/algo-with-me-api/src/auth/services/auth.service.ts
  be/algo-with-me-api/src/competition/competition.module.ts
  be/algo-with-me-api/src/competition/dto/create-submission.dto.ts
  be/algo-with-me-api/src/competition/dto/problem.response.dto.ts
  be/algo-with-me-api/src/competition/dto/score-result.dto.ts
  be/algo-with-me-api/src/competition/gateways/competition.gateway.ts
  be/algo-with-me-api/src/competition/services/competition.service.ts
  be/algo-with-me-api/src/competition/services/problem.service.ts
  be/algo-with-me-api/src/competition/tem.consumer.ts
Labels: BE

#111 [#82] 메인 페이지 추가 요구 기능
  frontend/src/apis/competitionList/index.ts
  frontend/src/apis/competitionList/types.ts
  frontend/src/apis/joinCompetition/index.ts
  frontend/src/apis/joinCompetition/types.ts
  frontend/src/components/Contest/CompetitionHeader.tsx
  frontend/src/components/Contest/ContestBreadCrumb.tsx
  frontend/src/components/Contest/ContestProblemSelector.tsx
  frontend/src/components/Main/Buttons/GoToCreateCompetitionLink.tsx
  frontend/src/components/Main/Buttons/JoinCompetitionButton.tsx
  frontend/src/components/Main/CompetitionList.tsx
  frontend/src/mockData.json
  frontend/src/pages/ContestPage.tsx
Labels: FE

#143 [#132] 대회 페이지 내의 웹소켓 연결 상태를 확인할 수 있는 기능
  frontend/src/components/Common/Loading.tsx
  frontend/src/components/Submission/Connecting.tsx
  frontend/src/components/Submission/SubmissionResult.tsx
  frontend/src/components/Timer/index.tsx
  frontend/src/hooks/competition/useCompetition.ts
  frontend/src/hooks/timer/useTimer.ts
  frontend/src/pages/ContestPage.tsx
  frontend/src/utils/date/index.ts
Labels: FE

#150 [#131] 대회 종료시 대시보드로 이동 기능
  frontend/src/components/SocketTimer/index.tsx
  frontend/src/components/Submission/Connecting.tsx
  frontend/src/hooks/timer/useSocketTimer.ts
  frontend/src/pages/ContestPage.tsx
Labels: FE

#149 [#138] 대회 세부정보 페이지 생성
  frontend/src/components/CompetitionDetail/AfterCompetition.tsx
  frontend/src/components/CompetitionDetail/BeforeCompetition.tsx
  frontend/src/components/CompetitionDetail/Buttons/EnterCompetitionButton.tsx
  frontend/src/components/CompetitionDetail/CompetitionDetailContent.tsx
  frontend/src/components/CompetitionDetail/CompetitionDetailInfo.tsx
  frontend/src/components/CompetitionDetail/DuringCompetition.tsx
  frontend/src/components/CompetitionDetail/ProblemList.tsx
  frontend/src/pages/CompetitionDetailPage.tsx
  frontend/src/router.tsx
  frontend/src/utils/date/index.ts
Labels: FE

#155 [#139] 대회 세부정보 페이지 추가 구현
  frontend/src/apis/competitions/types.ts
  frontend/src/components/CompetitionDetail/AfterCompetition.tsx
  frontend/src/components/CompetitionDetail/BeforeCompetition.tsx
  frontend/src/components/CompetitionDetail/CompetitionMembersInfo.tsx
  frontend/src/components/CompetitionDetail/DuringCompetition.tsx
  frontend/src/hooks/competition/useCompetition.ts
Labels: FE

#161 [#133] 대회 페이지 레이아웃을 프로그래머스처럼 수정
  frontend/panda.config.ts
  frontend/src/components/Common/Button.tsx
  frontend/src/components/Common/HStack.tsx
  frontend/src/components/Common/Space.tsx
  frontend/src/components/Common/VStack.tsx
  frontend/src/components/Common/index.ts
  frontend/src/components/Competition/CompetitionBreadCrumb.tsx
  frontend/src/components/Competition/CompetitionContext.ts
  frontend/src/components/Competition/CompetitionHeader.tsx
  frontend/src/components/Competition/CompetitionProblemSelector.tsx
  frontend/src/components/Competition/CompetitionProvider.tsx
  frontend/src/components/Contest/CompetitionHeader.tsx
  frontend/src/components/Contest/ContestProblemSelector.tsx
  frontend/src/components/Editor/Editor.tsx
  frontend/src/components/Layout/PageLayout.tsx
  frontend/src/components/Main/Buttons/ViewDashboardButton.tsx
  frontend/src/components/Main/CompetitionList.tsx
  frontend/src/components/Problem/ProblemHeader.tsx
  frontend/src/components/Problem/ProblemViewer.tsx
  frontend/src/components/Simulation/SimulationExecButton.tsx
  frontend/src/components/Simulation/SimulationInputModal.tsx
  frontend/src/components/SocketTimer/index.tsx
  frontend/src/components/Submission/SubmissionButton.tsx
  frontend/src/components/Submission/SubmissionResult.tsx
  frontend/src/components/Submission/index.tsx
  frontend/src/components/Submission/types.ts
  frontend/src/constants/index.ts
  frontend/src/hooks/timer/useSocketTimer.ts
  frontend/src/index.css
  frontend/src/pages/CompetitionPage.tsx
  frontend/src/pages/ContestPage.tsx
  frontend/src/router.tsx
Labels: FE

#159 [#141] 대시보드 페이지
  frontend/src/components/Common/BreadCrumb.tsx
  frontend/src/components/Common/Socket/SocketContext.ts
  frontend/src/components/Common/Socket/SocketProvider.tsx
  frontend/src/components/Common/Socket/index.ts
  frontend/src/components/Competition/CompetitionContext.ts
  frontend/src/components/Competition/CompetitionHeader.tsx
  frontend/src/components/Competition/CompetitionProvider.tsx
  frontend/src/components/CompetitionDetail/Buttons/EnterCompetitionButton.tsx
  frontend/src/components/Dashboard/Buttons/OpenDashboardModalButton.tsx
  frontend/src/components/Dashboard/DashboardModal.tsx
  frontend/src/components/Dashboard/DashboardTable.tsx
  frontend/src/components/Dashboard/TempDashboardTable.tsx
  frontend/src/components/Dashboard/mockData.tsx
  frontend/src/components/Login/index.tsx
  frontend/src/components/Main/Buttons/GoToCreateCompetitionLink.tsx
  frontend/src/components/Main/Buttons/JoinCompetitionButton.tsx
  frontend/src/components/SocketTimer/index.tsx
  frontend/src/components/Submission/SubmissionButton.tsx
  frontend/src/components/Submission/SubmissionResult.tsx
  frontend/src/hooks/competition/index.ts
  frontend/src/hooks/competition/useCompetition.ts
  frontend/src/hooks/dashboard/index.ts
  frontend/src/hooks/dashboard/types.ts
  frontend/src/hooks/dashboard/useParticipantDashboard.ts
  frontend/src/pages/CompetitionPage.tsx
  frontend/src/pages/DashboardPage.tsx
  frontend/src/router.tsx
  frontend/src/utils/date/index.ts
Labels: FE
